logging:
  level:
    org.springframework: INFO

# DataSource Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poseidon-prod
    username: root
    password: admin
    initialize: true

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
